logging:
    level:
        org:
            hibernate:
                SQL: debug
                type: trace
server:
    port: 8080
spring:
    application:
        name: Recipe-Realm
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/recipeRealm?createDatabaseIfNotExist=true
        username: root
        #password:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
        show-sql: true

spring-doc:
    api-docs:
        path: /api-docs

debug: false

secret-key: 3236464233324341314236393235454146313246353844464642353838

#localhost:8080/swagger-ui/index.html